name             'aggregator'
maintainer       'PE, pf.'
maintainer_email 'philippe.eychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures aggregator'
long_description 'Installs/Configures aggregator'
version          '0.1.0'
depends          'chef-iproute2'
